import React from 'react';

interface IconPickerProps {
  selectedIcon: string;
  onIconSelect: (icon: string) => void;
}

const ROOM_ICONS = [
  { id: 'chat', name: 'Chat', emoji: '💬' },
  { id: 'heart', name: 'Heart', emoji: '❤️' },
  { id: 'star', name: 'Star', emoji: '⭐' },
  { id: 'fire', name: 'Fire', emoji: '🔥' },
  { id: 'rocket', name: 'Rocket', emoji: '🚀' },
  { id: 'crown', name: 'Crown', emoji: '👑' },
  { id: 'diamond', name: 'Diamond', emoji: '💎' },
  { id: 'lightning', name: 'Lightning', emoji: '⚡' },
  { id: 'sun', name: 'Sun', emoji: '☀️' },
  { id: 'moon', name: 'Moon', emoji: '🌙' },
  { id: 'coffee', name: 'Coffee', emoji: '☕' },
  { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  { id: 'game', name: 'Game', emoji: '🎮' },
  { id: 'music', name: 'Music', emoji: '🎵' },
  { id: 'camera', name: 'Camera', emoji: '📷' },
  { id: 'book', name: 'Book', emoji: '📚' },
  { id: 'paint', name: 'Paint', emoji: '🎨' },
  { id: 'football', name: 'Football', emoji: '⚽' },
  { id: 'basketball', name: 'Basketball', emoji: '🏀' },
  { id: 'car', name: 'Car', emoji: '🚗' },
  { id: 'plane', name: 'Plane', emoji: '✈️' },
  { id: 'house', name: 'House', emoji: '🏠' },
  { id: 'tree', name: 'Tree', emoji: '🌳' },
  { id: 'flower', name: 'Flower', emoji: '🌸' },
  { id: 'cat', name: 'Cat', emoji: '🐱' },
  { id: 'dog', name: 'Dog', emoji: '🐶' },
  { id: 'fish', name: 'Fish', emoji: '🐠' },
  { id: 'butterfly', name: 'Butterfly', emoji: '🦋' },
  { id: 'rainbow', name: 'Rainbow', emoji: '🌈' },
  { id: 'gift', name: 'Gift', emoji: '🎁' },
  // 新增30个图标
  { id: 'smile', name: 'Smile', emoji: '😊' },
  { id: 'laugh', name: 'Laugh', emoji: '😂' },
  { id: 'love', name: 'Love', emoji: '🥰' },
  { id: 'wink', name: 'Wink', emoji: '😉' },
  { id: 'cool', name: 'Cool', emoji: '😎' },
  { id: 'thinking', name: 'Thinking', emoji: '🤔' },
  { id: 'party', name: 'Party', emoji: '🎉' },
  { id: 'balloon', name: 'Balloon', emoji: '🎈' },
  { id: 'cake', name: 'Cake', emoji: '🎂' },
  { id: 'icecream', name: 'Ice Cream', emoji: '🍦' },
  { id: 'hamburger', name: 'Hamburger', emoji: '🍔' },
  { id: 'taco', name: 'Taco', emoji: '🌮' },
  { id: 'sushi', name: 'Sushi', emoji: '🍣' },
  { id: 'beer', name: 'Beer', emoji: '🍺' },
  { id: 'wine', name: 'Wine', emoji: '🍷' },
  { id: 'popcorn', name: 'Popcorn', emoji: '🍿' },
  { id: 'donut', name: 'Donut', emoji: '🍩' },
  { id: 'cookie', name: 'Cookie', emoji: '🍪' },
  { id: 'lollipop', name: 'Lollipop', emoji: '🍭' },
  { id: 'chocolate', name: 'Chocolate', emoji: '🍫' },
  { id: 'trophy', name: 'Trophy', emoji: '🏆' },
  { id: 'medal', name: 'Medal', emoji: '🏅' },
  { id: 'ticket', name: 'Ticket', emoji: '🎫' },
  { id: 'dice', name: 'Dice', emoji: '🎲' },
  { id: 'chess', name: 'Chess', emoji: '♟️' },
  { id: 'puzzle', name: 'Puzzle', emoji: '🧩' },
  { id: 'magic', name: 'Magic', emoji: '🪄' },
  { id: 'crystal', name: 'Crystal', emoji: '🔮' },
  { id: 'key', name: 'Key', emoji: '🗝️' },
  { id: 'lock', name: 'Lock', emoji: '🔒' },
  { id: 'unlock', name: 'Unlock', emoji: '🔓' },
  { id: 'bell', name: 'Bell', emoji: '🔔' },
  { id: 'alarm', name: 'Alarm', emoji: '⏰' },
  { id: 'stopwatch', name: 'Stopwatch', emoji: '⏱️' },
  { id: 'hourglass', name: 'Hourglass', emoji: '⏳' },
  { id: 'compass', name: 'Compass', emoji: '🧭' },
  { id: 'globe', name: 'Globe', emoji: '🌍' },
  { id: 'map', name: 'Map', emoji: '🗺️' },
  { id: 'mountain', name: 'Mountain', emoji: '⛰️' },
  { id: 'volcano', name: 'Volcano', emoji: '🌋' },
  { id: 'island', name: 'Island', emoji: '🏝️' },
  { id: 'desert', name: 'Desert', emoji: '🏜️' },
  { id: 'snowflake', name: 'Snowflake', emoji: '❄️' },
  { id: 'cloud', name: 'Cloud', emoji: '☁️' },
  { id: 'umbrella', name: 'Umbrella', emoji: '☂️' },
  { id: 'zap', name: 'Zap', emoji: '⚡' },
  { id: 'snowman', name: 'Snowman', emoji: '⛄' },
  { id: 'comet', name: 'Comet', emoji: '☄️' },
  { id: 'telescope', name: 'Telescope', emoji: '🔭' },
  { id: 'microscope', name: 'Microscope', emoji: '🔬' },
  { id: 'gear', name: 'Gear', emoji: '⚙️' },
  { id: 'hammer', name: 'Hammer', emoji: '🔨' },
  { id: 'wrench', name: 'Wrench', emoji: '🔧' },
  { id: 'nut', name: 'Nut', emoji: '🔩' },
  { id: 'link', name: 'Link', emoji: '🔗' },
  { id: 'chain', name: 'Chain', emoji: '⛓️' },
  { id: 'anchor', name: 'Anchor', emoji: '⚓' },
  { id: 'sailboat', name: 'Sailboat', emoji: '⛵' },
  { id: 'ship', name: 'Ship', emoji: '🚢' },
  { id: 'ferris', name: 'Ferris Wheel', emoji: '🎡' },
  { id: 'roller', name: 'Roller Coaster', emoji: '🎢' },
  { id: 'circus', name: 'Circus', emoji: '🎪' },
  { id: 'tent', name: 'Tent', emoji: '⛺' },
  { id: 'camping', name: 'Camping', emoji: '🏕️' },
  { id: 'hotel', name: 'Hotel', emoji: '🏨' },
  { id: 'hospital', name: 'Hospital', emoji: '🏥' },
  { id: 'school', name: 'School', emoji: '🏫' },
  { id: 'office', name: 'Office', emoji: '🏢' },
  { id: 'bank', name: 'Bank', emoji: '🏦' },
  { id: 'church', name: 'Church', emoji: '⛪' },
  { id: 'mosque', name: 'Mosque', emoji: '🕌' },
  { id: 'synagogue', name: 'Synagogue', emoji: '🕍' },
  { id: 'temple', name: 'Temple', emoji: '🛕' },
  { id: 'castle', name: 'Castle', emoji: '🏰' },
  { id: 'bridge', name: 'Bridge', emoji: '🌉' },
  { id: 'fountain', name: 'Fountain', emoji: '⛲' },
  { id: 'statue', name: 'Statue', emoji: '🗽' },
  { id: 'tower', name: 'Tower', emoji: '🗼' },
  { id: 'factory', name: 'Factory', emoji: '🏭' },
  { id: 'construction', name: 'Construction', emoji: '🏗️' },
  { id: 'crane', name: 'Crane', emoji: '🏗️' },
  { id: 'bulldozer', name: 'Bulldozer', emoji: '🚜' },
  { id: 'tractor', name: 'Tractor', emoji: '🚜' },
  { id: 'motorcycle', name: 'Motorcycle', emoji: '🏍️' },
  { id: 'bike', name: 'Bike', emoji: '🚲' },
  { id: 'scooter', name: 'Scooter', emoji: '🛴' },
  { id: 'skateboard', name: 'Skateboard', emoji: '🛹' },
  { id: 'bus', name: 'Bus', emoji: '🚌' },
  { id: 'truck', name: 'Truck', emoji: '🚚' },
  { id: 'van', name: 'Van', emoji: '🚐' },
  { id: 'taxi', name: 'Taxi', emoji: '🚕' },
  { id: 'police', name: 'Police Car', emoji: '🚔' },
  { id: 'ambulance', name: 'Ambulance', emoji: '🚑' },
  { id: 'firetruck', name: 'Fire Truck', emoji: '🚒' },
  { id: 'train', name: 'Train', emoji: '🚆' },
  { id: 'metro', name: 'Metro', emoji: '🚇' },
  { id: 'tram', name: 'Tram', emoji: '🚊' },
  { id: 'monorail', name: 'Monorail', emoji: '🚝' },
  { id: 'mountain_railway', name: 'Mountain Railway', emoji: '🚞' },
  { id: 'steam_locomotive', name: 'Steam Locomotive', emoji: '🚂' },
  { id: 'railway_car', name: 'Railway Car', emoji: '🚃' },
  { id: 'bullettrain', name: 'Bullet Train', emoji: '🚅' },
  { id: 'helicopter', name: 'Helicopter', emoji: '🚁' },
  { id: 'suspension_railway', name: 'Suspension Railway', emoji: '🚟' },
  { id: 'mountain_cableway', name: 'Mountain Cableway', emoji: '🚠' },
  { id: 'aerial_tramway', name: 'Aerial Tramway', emoji: '🚡' },
  { id: 'satellite', name: 'Satellite', emoji: '🛰️' },
  { id: 'rocket2', name: 'Rocket 2', emoji: '🚀' },
  { id: 'flying_saucer', name: 'Flying Saucer', emoji: '🛸' },
  { id: 'bellhop', name: 'Bellhop', emoji: '🛎️' },
  { id: 'luggage', name: 'Luggage', emoji: '🧳' },
  { id: 'hourglass_flowing', name: 'Hourglass Flowing', emoji: '⏳' },
  { id: 'watch', name: 'Watch', emoji: '⌚' },
  { id: 'alarm_clock', name: 'Alarm Clock', emoji: '⏰' },
  { id: 'stopwatch2', name: 'Stopwatch 2', emoji: '⏱️' },
  { id: 'timer', name: 'Timer', emoji: '⏲️' },
  { id: 'mantelpiece_clock', name: 'Mantelpiece Clock', emoji: '🕰️' },
  { id: 'twelve_oclock', name: 'Twelve O\'Clock', emoji: '🕛' },
  { id: 'twelve_thirty', name: 'Twelve Thirty', emoji: '🕧' },
  { id: 'one_oclock', name: 'One O\'Clock', emoji: '🕐' },
  { id: 'one_thirty', name: 'One Thirty', emoji: '🕜' },
  { id: 'two_oclock', name: 'Two O\'Clock', emoji: '🕑' },
  { id: 'two_thirty', name: 'Two Thirty', emoji: '🕝' },
  { id: 'three_oclock', name: 'Three O\'Clock', emoji: '🕒' },
  { id: 'three_thirty', name: 'Three Thirty', emoji: '🕞' },
  { id: 'four_oclock', name: 'Four O\'Clock', emoji: '🕓' },
  { id: 'four_thirty', name: 'Four Thirty', emoji: '🕟' },
  { id: 'five_oclock', name: 'Five O\'Clock', emoji: '🕔' },
  { id: 'five_thirty', name: 'Five Thirty', emoji: '🕠' },
  { id: 'six_oclock', name: 'Six O\'Clock', emoji: '🕕' },
  { id: 'six_thirty', name: 'Six Thirty', emoji: '🕡' },
  { id: 'seven_oclock', name: 'Seven O\'Clock', emoji: '🕖' },
  { id: 'seven_thirty', name: 'Seven Thirty', emoji: '🕢' },
  { id: 'eight_oclock', name: 'Eight O\'Clock', emoji: '🕗' },
  { id: 'eight_thirty', name: 'Eight Thirty', emoji: '🕣' },
  { id: 'nine_oclock', name: 'Nine O\'Clock', emoji: '🕘' },
  { id: 'nine_thirty', name: 'Nine Thirty', emoji: '🕤' },
  { id: 'ten_oclock', name: 'Ten O\'Clock', emoji: '🕙' },
  { id: 'ten_thirty', name: 'Ten Thirty', emoji: '🕥' },
  { id: 'eleven_oclock', name: 'Eleven O\'Clock', emoji: '🕚' },
  { id: 'eleven_thirty', name: 'Eleven Thirty', emoji: '🕦' }
];

const IconPicker: React.FC<IconPickerProps> = ({ selectedIcon, onIconSelect }) => {
  return (
    <div>
      <label className="block text-sm font-medium text-text-secondary mb-3">Room Icon</label>
      <div className="grid grid-cols-6 gap-2 max-h-40 overflow-y-auto">
        {ROOM_ICONS.map((icon) => (
          <button
            key={icon.id}
            type="button"
            onClick={() => onIconSelect(icon.id)}
            className={`w-8 h-8 flex items-center justify-center rounded-lg text-lg transition-all duration-200 ${
              selectedIcon === icon.id
                ? 'bg-highlight text-white scale-110 shadow-lg'
                : 'bg-accent text-text-primary hover:bg-accent/70 hover:scale-105'
            }`}
            title={icon.name}
          >
            {icon.emoji}
          </button>
        ))}
      </div>
    </div>
  );
};

export default IconPicker;
